config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  root 'static_pages#home'
  get '/contact', to: 'static_pages#contact'
  get '/help', to: "static_pages#help"
  get '/about', to: "static_pages#about"
  get '/signup', to: "users#new"
  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts do
    member do
      put "like"    => "microposts#like"
      put "unlike"  => "microposts#unlike"
    end
  end
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :microposts,          only: [:create, :destroy]
  resources :relationships,       only: [:create, :destroy]

  
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  acts_as_votable
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  mount_uploader :picture, PictureUploader
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  validate :picture_size 
  
  
  private
  
    def picture_size
      if picture.size > 5.megabytes
       errors.add(:picture, "should be less than 5 mb")
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :destroy]
  before_action :correct_user,   only: [:destroy]
  before_action :set_posts,      only: [:like, :unlike]
  

  def create
    @micropost = current_user.microposts.build(micropost_params)
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    flash[:success] = "Micropost deleted"
    redirect_to request.referrer || root_url
  end
  
  def like
    @post.liked_by current_user
    redirect_to request.referrer
  end
  
  def unlike
    @post.disliked_by current_user
    redirect_to request.referrer
  end

  
  private
  
    def set_posts
      @post = Micropost.find_by(id: params[:id])
    end
  
    def micropost_params
      params.require(:micropost).permit(:content, :picture)
    end
    
    def correct_user
      @micropost = current_user.microposts.find_by(id: params[:id])
      redirect_to root_url if @micropost.nil?
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content">
    <%= micropost.content %>
    <%= image_tag micropost.picture.url if micropost.picture? %>
  </span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <%= link_to "Like", like_micropost_path(micropost), method: :put %>
  <span><%= micropost.get_likes.size %></span>
  <%= link_to "Dislike", unlike_micropost_path(micropost), method: :put %>
  <span><%= micropost.get_dislikes.size %></span>
  <% if current_user == micropost.user %>
    <span> | </span>
    <%= link_to "delete", micropost, method: :delete,
                          data: { confirm: "You sure?" } %>
  <% end %>
</li>